services:
  - type: worker
    name: webscan-bot
    runtime: python
    buildCommand: ./build.sh
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: ADMIN_ID
        value: your_admin_id_here
